### ISSUE TITLE
S2 technical verification -one-off stress test

### ISSUE THREAD

**Issue by LynnHeeley** [jncc/s2-ard-processor#8]
stress test - DDS team can process orbit 80 or 37 for a full swath (one-off task)

Try running multiple big swaths through (30+ granules) just the ARD processing bit

**Comment by felixMasonJncc** [comment]
Choose several large swathes and run through to basic arcsi ARD on the target infrastructure. 

This can use the basic arcsi base container. It should be run on aws initially to give a base time.

**Comment by felixMasonJncc** [comment]
Large swathes from Dan:

26/6/18

S2A_MSIL1C_20180626T110621_N0206_R137_T30UYC_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UYD_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UYE_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UXC_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UXE_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UWC_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UXD_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UXB_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UXF_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UYB_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UWB_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UWD_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UWE_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UWF_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UVC_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T30UVB_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T31UCT_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T31UCU_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T31UCS_20180626T113415

S2A_MSIL1C_20180626T110621_N0206_R137_T31UDU_20180626T113415

 

28/6/18

S2A_MSIL1C_20180628T115401_N0206_R023_T29VPD_20180628T121737

S2A_MSIL1C_20180628T115401_N0206_R023_T29VNE_20180628T121737

S2A_MSIL1C_20180628T115401_N0206_R023_T29VPC_20180628T121737

S2A_MSIL1C_20180628T115401_N0206_R023_T29VPE_20180628T121737

S2A_MSIL1C_20180628T115401_N0206_R023_T30VUJ_20180628T121737

S2A_MSIL1C_20180628T115401_N0206_R023_T29VND_20180628T121737

S2A_MSIL1C_20180628T115401_N0206_R023_T30VVK_20180628T121737

S2A_MSIL1C_20180628T115401_N0206_R023_T30VUK_20180628T121737

S2A_MSIL1C_20180628T115401_N0206_R023_T30VUH_20180628T121737

S2A_MSIL1C_20180628T115401_N0206_R023_T29UPB_20180628T121737

 

30/6/18

S2B_MSIL1C_20180630T114349_N0206_R123_T30VWN_20180630T165917

S2B_MSIL1C_20180630T114349_N0206_R123_T30VXN_20180630T165917

S2B_MSIL1C_20180630T114349_N0206_R123_T30VWM_20180630T165917

S2B_MSIL1C_20180630T114349_N0206_R123_T30VXM_20180630T165917

S2B_MSIL1C_20180630T114349_N0206_R123_T30VVJ_20180630T165917

S2B_MSIL1C_20180630T114349_N0206_R123_T30VVH_20180630T165917

S2B_MSIL1C_20180630T114349_N0206_R123_T30VUH_20180630T165917

S2B_MSIL1C_20180630T114349_N0206_R123_T30UVG_20180630T165917

S2B_MSIL1C_20180630T114349_N0206_R123_T30UUG_20180630T165917

 

24/2/18

S2B_MSIL1C_20180224T112109_N0206_R037_T29UQS_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UUB_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UVB_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UVC_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UVE_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UVG_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UWB_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UWC_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UWD_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UWE_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UWF_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UWG_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UXB_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UXC_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UXD_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UXE_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UXF_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UXG_20180224T164834

S2B_MSIL1C_20180224T112109_N0206_R037_T30UVD_20180224T164834

 

11/2/18

S2B_MSIL1C_20180211T111159_N0206_R137_T30UWC_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UWF_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UWG_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UXB_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UXC_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UXD_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UXF_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UXG_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UYB_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UYC_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T30UYE_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T31UCS_20180211T133150

S2B_MSIL1C_20180211T111159_N0206_R137_T31UCT_20180211T133150

**Comment by CathyJinJNCC** [comment]
No longer needed
